### ISSUE TITLE
load data in to endpoint

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-explore#2]
Data should be indexed in multiple tables that aggregate related information.
Each table would represented an independent variable and it's corresponding observations.

**Comment by ntrrgc** [comment]
Since https://github.com/HEPData/hepdata-explore/commit/2701fb73d81ae69da329fd8f53f3ce78f4116912 the data for each independent variable is stored in a different file. The client only downloads one of these files when an independent variable is chosen.
