### ISSUE TITLE
allow for download of the filtered data records

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-explore#5]
**NOTE** that the full data would need to be downloaded for this to be useful. At the minute the errors are missing.

**Comment by ntrrgc** [comment]
> the errors are missing

What do you mean?

**Comment by eamonnmag** [comment]
Well, if you were to download the data as it is stored now in your flat structure, you wouldn't have the associated errors for each data point. This would need to be present in the final downloaded data set.

**Comment by ntrrgc** [comment]
Ah, _those_ errors. Understood.

**Comment by ntrrgc** [comment]
What would be downloaded? The data matching some filter, even from different publications, or entire tables from a data point?

**Comment by eamonnmag** [comment]
Yeah, the data matching the filter, regardless of the publication. The thing we need though is to have some provenance, so that the researcher knows which data came from where. 

There should be the option to view the publications containing the data though, and the tables they came from. Then the option to download whatever they please.

**Comment by ntrrgc** [comment]
What would be the use case for the download of filtered data?

**Comment by eamonnmag** [comment]
The researcher could find all data matching a particular query, e.g. energy range, then perform a new analysis based on the aggregated data from the experimental data provided by HEPData.

**Comment by ntrrgc** [comment]
I have modified my `flatten.py` script to aggregate all the error labels in my sample data set. This is the result.

```
{'sys,detector', 'sys,TPA uncertainty', 'sys,centrality', 'sys,background', 
'stat', 'sys,extr', 'sys,RCOLL uncertainty', 'sys,BR', 'sys,luminosity uncertainty', 
'sys,theo', 'sys,lumi', 'sys,norm', 'sys'}
```

Not that many. Should those labels be used verbatim or rather go through some normalization process (e.g. consider all `sys` errors the same)? Do you have a preferred export format for filtered data (e.g. CSV, JSON, YAML)?

**Comment by eamonnmag** [comment]
I think having them in their full form like this makes sense. sys is like the parent, then TPA uncertainty, detector etc are children of the more general systematic error.

**Comment by ntrrgc** [comment]
This has been implemented in https://github.com/HEPData/hepdata-explore/commit/aef1dae07bc32841af4bbeac0807413583d2eeb5.
